server:
  port: 7000
spring:
  application:
    name: api-gateway
  profiles:
    active: @profileActive@
  cloud:
    nacos:
      discovery:
        server-addr: 150.158.79.228:8848
    gateway:
      discovery:
        locator:
          enabled: true # 让gateway可以发现nacos中的微服务
      routes: # 路由数组[路由 就是指定当请求满足什么条件的时候转到哪个微服务]
        - id: product_route # 当前路由的标识, 要求唯一
          order: 1 # 路由的优先级,数字越小级别越高
          uri: lb://service-product-${spring.profiles.active} # lb指的是从nacos中按照名称获取微服务,并遵循负载均衡策略
          predicates: # 断言(就是路由转发要满足的条件)
            - Path=/product-service/**  # 当请求路径满足Path指定的规则时,才进行路由转发
            - Before=2024-03-28T00:00:00.000+08:00 #限制请求时间在2024-03-28之前
            - Method=GET #限制请求方式为GET
            - Age=18,60 # 限制年龄只有在18到60岁之间的人能访问
          filters: # 过滤器,请求在传递过程中可以通过过滤器对其进行一定的修改
            - StripPrefix=1 # 转发之前去掉1层路径
#            - SetStatus=2000 # 修改返回状态
            - Log=true,false # 控制日志是否开启
